// Starter exercise library.
// Demonstration images are public-domain stills from the free-exercise-db project
// (github.com/yuhonas/free-exercise-db, released under The Unlicense). Every media_url
// was verified to return HTTP 200 + image/jpeg. A coach can one-click add these into
// their own exercise_library, then replace any image/video via Cloudinary later.

export type StarterExercise = {
  name: string;
  muscle_group: "Chest" | "Back" | "Legs" | "Shoulders" | "Arms" | "Core" | "Glutes" | "Full body";
  equipment: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  motion_type: "squat" | "hinge" | "push" | "pull" | "lunge" | "plank" | "curl" | "press" | "custom";
  media_url: string;
  instructions: string;
};

const BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

export const STARTER_EXERCISES: StarterExercise[] = [
  { name: "Barbell Bench Press", muscle_group: "Chest", equipment: "Barbell", difficulty: "intermediate", motion_type: "press", media_url: `${BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`, instructions: "Lie flat with eyes under the bar, feet planted, and a slight arch. Lower the bar to mid-chest with elbows about 45 degrees, then press up and slightly back over the shoulders." },
  { name: "Incline Dumbbell Press", muscle_group: "Chest", equipment: "Dumbbell", difficulty: "beginner", motion_type: "press", media_url: `${BASE}/Incline_Dumbbell_Press/0.jpg`, instructions: "Set the bench to 30-45 degrees and start with dumbbells at upper-chest level. Press up and slightly together until the arms extend, then lower under control to a deep stretch." },
  { name: "Dumbbell Bench Press", muscle_group: "Chest", equipment: "Dumbbell", difficulty: "beginner", motion_type: "press", media_url: `${BASE}/Dumbbell_Bench_Press/0.jpg`, instructions: "Lie flat with dumbbells at chest height and shoulder blades pinned to the bench. Press the weights up until arms are straight, then lower slowly to feel a stretch across the chest." },
  { name: "Push-Up", muscle_group: "Chest", equipment: "Bodyweight", difficulty: "beginner", motion_type: "push", media_url: `${BASE}/Pushups/0.jpg`, instructions: "Set hands slightly wider than shoulders with a straight line from head to heels. Lower until the chest nearly touches the floor with elbows tucked, then press back up without letting the hips sag." },
  { name: "Cable Crossover", muscle_group: "Chest", equipment: "Cable", difficulty: "beginner", motion_type: "push", media_url: `${BASE}/Cable_Crossover/0.jpg`, instructions: "Set the pulleys high, take a staggered stance, and hold a slight bend in the elbows. Sweep the handles down and together in front of the hips, squeezing the chest, then return to a stretch." },
  { name: "Bent-Over Barbell Row", muscle_group: "Back", equipment: "Barbell", difficulty: "intermediate", motion_type: "pull", media_url: `${BASE}/Bent_Over_Barbell_Row/0.jpg`, instructions: "Hinge to about 45 degrees with a flat back and the bar at arm's length. Pull to the lower ribs by driving the elbows back and squeezing the shoulder blades, then lower under control." },
  { name: "Pull-Up", muscle_group: "Back", equipment: "Bodyweight", difficulty: "intermediate", motion_type: "pull", media_url: `${BASE}/Pullups/0.jpg`, instructions: "Hang with an overhand, slightly wider-than-shoulder grip and shoulders set down and back. Pull your chest toward the bar until the chin clears, then lower fully under control without swinging." },
  { name: "Wide-Grip Lat Pulldown", muscle_group: "Back", equipment: "Cable", difficulty: "beginner", motion_type: "pull", media_url: `${BASE}/Wide-Grip_Lat_Pulldown/0.jpg`, instructions: "Grip wider than shoulders, sit tall, and secure the thighs under the pad. Pull the bar to the upper chest by driving the elbows down and back, then let it rise under control." },
  { name: "Seated Cable Row", muscle_group: "Back", equipment: "Cable", difficulty: "beginner", motion_type: "pull", media_url: `${BASE}/Seated_Cable_Rows/0.jpg`, instructions: "Sit tall with a slight knee bend and grip the handle at arm's length. Pull to the abdomen by driving the elbows back and pinching the shoulder blades, then extend under control." },
  { name: "Barbell Deadlift", muscle_group: "Back", equipment: "Barbell", difficulty: "intermediate", motion_type: "hinge", media_url: `${BASE}/Barbell_Deadlift/0.jpg`, instructions: "Stand with mid-foot under the bar, hinge to grip just outside the knees, and set a flat back. Drive through the floor to stand tall, keeping the bar close, then hinge back down under control." },
  { name: "Barbell Back Squat", muscle_group: "Legs", equipment: "Barbell", difficulty: "intermediate", motion_type: "squat", media_url: `${BASE}/Barbell_Squat/0.jpg`, instructions: "Rack the bar across the upper back, feet shoulder-width, and brace hard. Sit down and back to at least parallel with knees tracking over the toes, then drive through mid-foot to stand." },
  { name: "Front Squat", muscle_group: "Legs", equipment: "Barbell", difficulty: "intermediate", motion_type: "squat", media_url: `${BASE}/Front_Squat_Clean_Grip/0.jpg`, instructions: "Hold the bar across the front delts with elbows high and feet shoulder-width. Descend straight down keeping the torso upright and elbows lifted, then drive up through the heels." },
  { name: "Leg Press", muscle_group: "Legs", equipment: "Machine", difficulty: "beginner", motion_type: "squat", media_url: `${BASE}/Leg_Press/0.jpg`, instructions: "Sit back with feet shoulder-width on the platform and knees in line with the toes. Lower under control to about 90 degrees, then press through the whole foot without hard-locking the knees." },
  { name: "Romanian Deadlift", muscle_group: "Legs", equipment: "Barbell", difficulty: "intermediate", motion_type: "hinge", media_url: `${BASE}/Romanian_Deadlift/0.jpg`, instructions: "Hold the bar at the hips with a soft knee bend. Push the hips back to slide the bar down the thighs until you feel a hamstring stretch, then drive the hips forward to stand." },
  { name: "Lying Leg Curl", muscle_group: "Legs", equipment: "Machine", difficulty: "beginner", motion_type: "hinge", media_url: `${BASE}/Lying_Leg_Curls/0.jpg`, instructions: "Lie face down with the pad just above the heels and hips pressed into the bench. Curl the heels toward the glutes by squeezing the hamstrings, then lower slowly under control." },
  { name: "Barbell Walking Lunge", muscle_group: "Legs", equipment: "Barbell", difficulty: "beginner", motion_type: "lunge", media_url: `${BASE}/Barbell_Walking_Lunge/0.jpg`, instructions: "Set the bar across the upper back and step forward into a lunge until both knees reach about 90 degrees. Drive through the front heel into the next step, keeping the torso tall." },
  { name: "Standing Overhead Press", muscle_group: "Shoulders", equipment: "Barbell", difficulty: "intermediate", motion_type: "press", media_url: `${BASE}/Standing_Military_Press/0.jpg`, instructions: "Hold the bar at the front rack, hands just outside the shoulders, glutes and core braced. Press straight overhead, moving the head back then through, until the arms lock out." },
  { name: "Dumbbell Shoulder Press", muscle_group: "Shoulders", equipment: "Dumbbell", difficulty: "intermediate", motion_type: "press", media_url: `${BASE}/Dumbbell_Shoulder_Press/0.jpg`, instructions: "Sit or stand with dumbbells at shoulder height and palms forward. Press overhead until the arms extend and the dumbbells nearly touch, then lower under control to ear level." },
  { name: "Dumbbell Lateral Raise", muscle_group: "Shoulders", equipment: "Dumbbell", difficulty: "beginner", motion_type: "push", media_url: `${BASE}/Side_Lateral_Raise/0.jpg`, instructions: "Stand with dumbbells at your sides and a slight elbow bend. Raise the arms out to shoulder height leading with the elbows, then lower slowly without shrugging or swinging." },
  { name: "Front Dumbbell Raise", muscle_group: "Shoulders", equipment: "Dumbbell", difficulty: "beginner", motion_type: "push", media_url: `${BASE}/Front_Dumbbell_Raise/0.jpg`, instructions: "Hold dumbbells in front of the thighs with a slight elbow bend. Raise the arms forward to shoulder height while keeping the torso still, then lower under control." },
  { name: "Reverse Fly", muscle_group: "Shoulders", equipment: "Dumbbell", difficulty: "beginner", motion_type: "pull", media_url: `${BASE}/Reverse_Flyes/0.jpg`, instructions: "Hinge forward with a flat back holding light dumbbells beneath the chest. Raise the arms out to the sides with a fixed elbow bend, squeezing the rear delts, then lower slowly." },
  { name: "Barbell Curl", muscle_group: "Arms", equipment: "Barbell", difficulty: "beginner", motion_type: "curl", media_url: `${BASE}/Barbell_Curl/0.jpg`, instructions: "Stand tall with a shoulder-width underhand grip and elbows tucked. Curl the bar up by contracting the biceps while keeping the elbows pinned, then lower to full extension." },
  { name: "Dumbbell Bicep Curl", muscle_group: "Arms", equipment: "Dumbbell", difficulty: "beginner", motion_type: "curl", media_url: `${BASE}/Dumbbell_Bicep_Curl/0.jpg`, instructions: "Stand with a dumbbell in each hand, palms forward, elbows close to the torso. Curl up by flexing the biceps while keeping the upper arms still, then lower slowly to a full stretch." },
  { name: "Hammer Curl", muscle_group: "Arms", equipment: "Dumbbell", difficulty: "beginner", motion_type: "curl", media_url: `${BASE}/Alternate_Hammer_Curl/0.jpg`, instructions: "Hold dumbbells with a neutral grip, thumbs up, elbows at your sides. Curl one dumbbell up keeping the wrist neutral and the upper arm still, then lower and alternate." },
  { name: "Triceps Pushdown", muscle_group: "Arms", equipment: "Cable", difficulty: "beginner", motion_type: "push", media_url: `${BASE}/Triceps_Pushdown/0.jpg`, instructions: "Face a high pulley, grip the bar or rope, tuck the elbows tight. Extend the arms down until straight and squeeze the triceps, then let it rise only until the forearms reach parallel." },
  { name: "Close-Grip Bench Press", muscle_group: "Arms", equipment: "Barbell", difficulty: "intermediate", motion_type: "press", media_url: `${BASE}/Close-Grip_Barbell_Bench_Press/0.jpg`, instructions: "Lie flat and grip the bar about shoulder-width with elbows tucked close. Lower to the lower chest, then press up by extending the elbows to emphasize the triceps." },
  { name: "Plank", muscle_group: "Core", equipment: "Bodyweight", difficulty: "beginner", motion_type: "plank", media_url: `${BASE}/Plank/0.jpg`, instructions: "Set the forearms under the shoulders with a straight line from head to heels. Brace the abs and glutes, keeping the hips level without sagging, and breathe steadily while holding for time." },
  { name: "Crunch", muscle_group: "Core", equipment: "Bodyweight", difficulty: "beginner", motion_type: "custom", media_url: `${BASE}/Crunches/0.jpg`, instructions: "Lie on your back with knees bent and hands lightly behind the head. Curl the shoulder blades off the floor by contracting the abs, then lower slowly without yanking the neck." },
  { name: "Hanging Leg Raise", muscle_group: "Core", equipment: "Bodyweight", difficulty: "advanced", motion_type: "custom", media_url: `${BASE}/Hanging_Leg_Raise/0.jpg`, instructions: "Hang from a bar with shoulders active and legs straight. Raise the legs by curling the pelvis up toward the chest rather than swinging, then lower under control." },
  { name: "Russian Twist", muscle_group: "Core", equipment: "Bodyweight", difficulty: "intermediate", motion_type: "custom", media_url: `${BASE}/Russian_Twist/0.jpg`, instructions: "Sit with knees bent and torso leaned back to engage the abs. Rotate side to side, bringing the hands or a weight across the body while keeping the chest up and moving with control." },
  { name: "Cable Crunch", muscle_group: "Core", equipment: "Cable", difficulty: "beginner", motion_type: "custom", media_url: `${BASE}/Cable_Crunch/0.jpg`, instructions: "Kneel below a high pulley holding the rope beside the head. Crunch down by rounding the spine and contracting the abs, keeping the hips fixed, then rise under control." },
  { name: "Barbell Hip Thrust", muscle_group: "Glutes", equipment: "Barbell", difficulty: "intermediate", motion_type: "hinge", media_url: `${BASE}/Barbell_Hip_Thrust/0.jpg`, instructions: "Sit with the upper back against a bench and the bar over the hips, feet flat. Drive through the heels to lift the hips until the torso is parallel to the floor, squeezing the glutes hard." },
  { name: "Barbell Glute Bridge", muscle_group: "Glutes", equipment: "Barbell", difficulty: "intermediate", motion_type: "hinge", media_url: `${BASE}/Barbell_Glute_Bridge/0.jpg`, instructions: "Lie on the floor with the bar over the hips and knees bent. Push through the heels to raise the hips into a straight line from knees to shoulders, then lower slowly keeping the ribs down." },
  { name: "Single-Leg Glute Bridge", muscle_group: "Glutes", equipment: "Bodyweight", difficulty: "beginner", motion_type: "hinge", media_url: `${BASE}/Single_Leg_Glute_Bridge/0.jpg`, instructions: "Lie on your back with one knee bent and the other leg extended. Drive through the planted heel to lift the hips level, squeezing the working glute, then lower under control." },
  { name: "Cable Glute Kickback", muscle_group: "Glutes", equipment: "Cable", difficulty: "intermediate", motion_type: "hinge", media_url: `${BASE}/One-Legged_Cable_Kickback/0.jpg`, instructions: "Attach an ankle strap to a low pulley and hinge slightly forward. Kick the working leg straight back by squeezing the glute with a soft knee, then return without swinging." },
  { name: "Glute Kickback", muscle_group: "Glutes", equipment: "Bodyweight", difficulty: "beginner", motion_type: "hinge", media_url: `${BASE}/Glute_Kickback/0.jpg`, instructions: "Start on all fours with hands under the shoulders and knees under the hips. Drive one heel toward the ceiling by extending the hip and squeezing the glute, then lower without arching." },
  { name: "Clean and Press", muscle_group: "Full body", equipment: "Barbell", difficulty: "intermediate", motion_type: "press", media_url: `${BASE}/Clean_and_Press/0.jpg`, instructions: "From a hip hinge, explosively pull the bar up and catch it at the front rack. Once stable, brace and press the bar overhead to lockout, then return under control." },
  { name: "Kettlebell Thruster", muscle_group: "Full body", equipment: "Kettlebell", difficulty: "intermediate", motion_type: "squat", media_url: `${BASE}/Kettlebell_Thruster/0.jpg`, instructions: "Hold the kettlebells at the shoulders and squat to at least parallel. Drive up explosively and use the momentum to press the weights overhead, then lower back and squat again." },
  { name: "Kettlebell Swing", muscle_group: "Full body", equipment: "Kettlebell", difficulty: "intermediate", motion_type: "hinge", media_url: `${BASE}/One-Arm_Kettlebell_Swings/0.jpg`, instructions: "Hinge at the hips and hike the kettlebell back between the legs. Snap the hips forward to float the bell to chest height with a relaxed arm, then let it swing back into the next hinge." },
  { name: "Mountain Climber", muscle_group: "Full body", equipment: "Bodyweight", difficulty: "beginner", motion_type: "custom", media_url: `${BASE}/Mountain_Climbers/0.jpg`, instructions: "Start in a high plank with hands under the shoulders and a braced core. Drive one knee toward the chest, then switch legs quickly while keeping the hips low and level." },
];
